### PR TITLE
Add tests to new macros part2

### PR DESCRIPTION
**Pull request by Gnaymie**

### CODE REVIEW

**Comment by DominicPazzulaFRG** [comment]
let's discuss Drawdowns vs Drawdown_Peak.  You delete one for the other, but the code looks different?  Were the results the same?  If so, which code was more efficient (ran faster, less prone to error)?  I personally prefer the name "Drawdowns" to "Drawdown_Peak" but that is just an opinion.

**Comment by Gnaymie** [comment]
These two generate the same results. But the code in previous Drawdowns are more efficient, so I keep  that, but change the name Drawdowns to Drawdown_Peak, because the R package documented Drawdown_Peak. But it's only a name, we can choose either one.

**Comment by Gnaymie** [comment]
And I'm going to keep the name Drawdowns and change all Drawdown_Peak in our package.

**Comment by DominicPazzulaFRG** [comment]
That sounds good to me.  Please let me know when you have the changes in here and I will merge.

**Comment by DominicPazzulaFRG** [comment]
There are conflicts with other code so I cannot automatically merge.  I will close this pull request.  Please merge your changes with the main repository and resubmit.

**Pull request closed without merging**
